name: Build React.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Set environment variables
        run: |
          cat > .env << 'EOF'
          VITE_API_URL=${{ vars.VITE_API_URL }}
          EOF

      - name: Build React.js app
        run: npm run build

      - name: Push build dist
        run: |
          git config --global user.name "${{ vars.GH_USERNAME }}"
          git config --global user.email "${{ vars.GH_EMAIL }}"
          git clone --branch main https://${{ secrets.GH_PAT }}@github.com/zenlab-teams/zenlab-perceptron-frontend-build.git dist-repository
          rm -rf dist-repository/dist
          cp -R dist dist-repository/dist
          cd dist-repository
          git add .
          git commit -m "Build $(date +'%Y%m%d%H%M') of github.com/zenlab-teams/zenlab-perceptron-frontend/commit/${{ github.sha }}"
          git push
